name: Python CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # =========================
  # CI - TEST ON UBUNTU
  # =========================
  test-python:
    name: CI - Python Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Check Python syntax
        run: |
          python -m py_compile "Account Trnx.py"

      - name: Test Ubuntu Runner
        run: |
          echo "CI is running successfully on Ubuntu"
          python --version
          echo "Runner OS:"
          uname -a


  # =========================
  # CD - TEST WINDOWS VM
  # =========================
  deploy-test:
    name: CD - Windows VM Test
    needs: test-python
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Test Windows VM Runner
        run: |
          echo "CD is running on my Windows VM"
          python --version
          hostname
          echo "Windows VM runner is working successfully"