name: Python CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # =========================
  # CI - TEST ON UBUNTU
  # =========================
  test-python:
    name: CI - Python Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Check Python syntax
        run: |
          python -m py_compile "Account Trnx.py"

      - name: Test Ubuntu Runner
        run: |
          echo "CI is running successfully on Ubuntu"
          python --version
          echo "Runner OS:"
          uname -a


  # =========================
  # CD - DEPLOY TO TEST
  # =========================
  deploy-test:
    name: CD - Deploy to TEST
    needs: test-python
    runs-on: self-hosted

    steps:

      - name: Deploy code to TEST
        shell: powershell
        run: |
          $testPath = "C:\Users\Administrator\Desktop\Zoho books\Zoho python code\Financial_DB_TEST"

          Write-Host "TEST path: $testPath"

          if (-not (Test-Path $testPath)) {
              New-Item -ItemType Directory -Path $testPath -Force
          }

          if (-not (Test-Path "$testPath\.git")) {

              Write-Host "TEST folder is not a Git repository."
              Write-Host "Cloning repository into TEST..."

              git clone "https://github.com/Arman-Siddiqui/Zoho-ETL-Finance.git" $testPath

          }
          else {

              Write-Host "TEST folder already contains Git repository."
              Write-Host "Updating TEST from GitHub..."

              git -C $testPath fetch origin
              git -C $testPath reset --hard origin/main

          }

          Write-Host "================================="
          Write-Host "TEST deployment completed"
          Write-Host "================================="

          Write-Host "Latest commit:"
          git -C $testPath log -1 --oneline

          Write-Host "Files in TEST:"
          Get-ChildItem $testPath